name = "telegram-stars-store-bot"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = true

[vars]
APP_ENV = "development"
BOT_WEBHOOK_PATH = "/webhook"
BOT_USERNAME = "replace_me_bot"
CRYPTO_PAY_WEBHOOK_PATH = "/webhook/crypto-pay/replace-me"
CRYPTO_PAY_API_BASE_URL = "https://pay.crypt.bot/api"
CRYPTO_PAY_ACCEPTED_ASSETS = "USDT,TON"
CRYPTO_PAY_SWAP_TO = "USDT"
APP_TIMEZONE = "Asia/Tashkent"
DEFAULT_LANGUAGE = "ru"
PAYMENT_CURRENCY = "XTR"
DEFAULT_EXCHANGE_RATE_RUB_PER_XTR = "1"

[observability]
enabled = true

[triggers]
crons = ["*/5 * * * *", "*/15 * * * *"]

[[kv_namespaces]]
binding = "APP_KV"
id = "bf750ddf262f4510808defa2baf17a53"
preview_id = "9185ce6c3dc140618a4ccd47c9564269"

[[d1_databases]]
binding = "BOT_DB"
database_name = "telegram-stars-store-bot-development"
database_id = "73d268cd-78ba-4890-9751-a8b840e0a114"

[env.staging]
name = "telegram-stars-store-bot-staging"

[env.staging.vars]
APP_ENV = "staging"
BOT_WEBHOOK_PATH = "/webhook"
BOT_USERNAME = "replace_me_bot"
CRYPTO_PAY_WEBHOOK_PATH = "/webhook/crypto-pay/replace-me"
CRYPTO_PAY_API_BASE_URL = "https://pay.crypt.bot/api"
CRYPTO_PAY_ACCEPTED_ASSETS = "USDT,TON"
CRYPTO_PAY_SWAP_TO = "USDT"
APP_TIMEZONE = "Asia/Tashkent"
DEFAULT_LANGUAGE = "ru"
PAYMENT_CURRENCY = "XTR"
DEFAULT_EXCHANGE_RATE_RUB_PER_XTR = "1"
CATALOG_IMAGE_URL = "https://cdn.jsdelivr.net/gh/shukurillaevumar/e-commerce-tg-bot@main/public/CatalogImg.png"


[[env.staging.kv_namespaces]]
binding = "APP_KV"
id = "039bdbff78eb47098eef03efc9e4ce8c"
preview_id = "77c880bab59141fbb35747aeaf36c7fa"

[[env.staging.d1_databases]]
binding = "BOT_DB"
database_name = "telegram-stars-store-bot-staging"
database_id = "b0e93450-31ac-4335-81e6-db66c85cc420"

[env.staging.triggers]
crons = ["*/5 * * * *", "*/15 * * * *"]

[env.production]
name = "telegram-stars-store-bot-production"

[env.production.vars]
APP_ENV = "production"
BOT_WEBHOOK_PATH = "/webhook"
BOT_USERNAME = "replace_me_bot"
CRYPTO_PAY_WEBHOOK_PATH = "/webhook/crypto-pay/replace-me"
CRYPTO_PAY_API_BASE_URL = "https://pay.crypt.bot/api"
CRYPTO_PAY_ACCEPTED_ASSETS = "USDT,TON"
CRYPTO_PAY_SWAP_TO = "USDT"
APP_TIMEZONE = "Asia/Tashkent"
DEFAULT_LANGUAGE = "ru"
PAYMENT_CURRENCY = "XTR"
DEFAULT_EXCHANGE_RATE_RUB_PER_XTR = "1"
CATALOG_IMAGE_URL = "https://cdn.jsdelivr.net/gh/shukurillaevumar/e-commerce-tg-bot@main/public/CatalogImg.png"

[[env.production.kv_namespaces]]
binding = "APP_KV"
id = "25257b96974b4d429dd83fb01e42410c"

[[env.production.d1_databases]]
binding = "BOT_DB"
database_name = "telegram-stars-store-bot-production"
database_id = "73d268cd-78ba-4890-9751-a8b840e0a114"

[env.production.triggers]
crons = ["*/5 * * * *", "*/15 * * * *"]
